name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/cache@v4
      with:      
        # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      
    - name: Install Dependencies
      run: npm install
      
    - name: Build Next.js App
      run: npm run build
      
    - name: Push to Separate Branch
      run: |
          # Set up Git config
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Create a commit message with the commit hash
          COMMIT_MESSAGE="Auto-deploy latest build (commit: $COMMIT_HASH)"
          
          # Switch to the deploy branch
          git checkout -f gh-pages
          
          # Create a temporary directory and move the out contents into it
          mkdir temp_out
          mv out/* temp_out/
          
          # Remove all files in the deploy branch and move the out contents back to the root directory
          git rm -r .
          mv temp_out/* .
          rm -r temp_out
          
          # Add a .nojekyll file to the root directory
          touch .nojekyll      
          
          # Add all changes, commit with the dynamic message, and push to the deploy branch
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push -u origin deploy -f
